export const VALIDATION_CRITERIA = {
  emailMaxLength: 100,
  passwordMinLength: 4,
  passwordMaxLength: 20,
  nameMinLength: 2,
  nameMaxLength: 40,
  smallNameMinLength: 2,
  smallNameMaxLength: 50,
  subTitleMinLength: 2,
  subTitleMaxLength: 150,
  titleMinLength: 2,
  titleMaxLength: 60,
  phoneMinLength: 8,
  phoneMaxLength: 14,
  locationMinLength: 2,
  locationMaxLength: 1000,
  priceMinLength: 1,
  priceMaxLength: 10,
  zipCodeMinLength: 4,
  zipCodeMaxLength: 12,
  maxRange: 100000,
  minRange: 0,
  minTime: 0,
  maxTime: 500,
  calorieMinLength: 1,
  calorieMaxLength: 10000,
  workoutCodeMinLength: 1,
  workoutCodeMaxLength: 20,
  MaxNoOfworkouts:10,
  MinNoOfworkouts:3,
  MinPoint:0,
  MaxPoint:1000,
  textAreaMaxLength:500
};
